# Generated by Django 5.1.3 on 2024-11-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0003_uploadimage_ai_content_uploadimage_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='ai_content',
            new_name='translate_content',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='edit_content',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
