# Generated by Django 5.1.3 on 2024-11-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_rename_ai_content_uploadimage_translate_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='translate_content',
            new_name='translated_content',
        ),
    ]
