# Generated by Django 5.1.3 on 2024-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0005_rename_translate_content_uploadimage_translated_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='title',
            field=models.TextField(default='未填入標題', max_length=100),
        ),
    ]
