# Generated by Django 5.1.3 on 2024-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0006_alter_uploadimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
