# Generated by Django 5.1.3 on 2024-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_uploadimage_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='ai_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='edit_content',
            field=models.TextField(default=''),
        ),
    ]
