# Generated by Django 5.1.3 on 2024-11-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='選項',
        ),
        migrations.AlterModelTable(
            name='question',
            table='問題',
        ),
    ]
